project:
  module: github.com/username/my_api
  user_model_name: User  # Name of the user model struct
  repository_name: UserRepository  # Repository interface name to use


# ============================================
# FCM CONFIGURATION
# ============================================
fcm:
  enabled: true
  credentials_path_env: FCM_CREDENTIALS_PATH
  save_to_database: true
  project_id_env: FCM_PROJECT_ID
  admin_topic_env: admin_default_stogne
  controller:
    enabled: true
    middleware: []
    base_path: /api
    SendFCM:
      enabled: true
      middleware: []
      path: /send-fcm
    SubscribeToTopic:
      enabled: true
      middleware: []
      path: /subscribe-to-topic

  web_handler:
    enabled: true
    template: ''
    middleware: []
    permissions: [post.view.user]
    context:
      needs_user: true
      needs_csrf: true
      needs_perms: true
      needs_dashbase: true
      needs_translations: true
      # base_translations: PostBase
      # extra_translations: [CommonTranslations]
      user_config:
        use_repo: true
        repo_name: userRepo
        method: GetByID
        get_all_method: GetAll
        get_user_by_token_method: GetUserByToken
      # custom_data:
        # - name: categories
        #   var: categories
        #   repo: Category
        #   method: GetAll
        #   args: []
        #   marshal: true
    GetNotificationPage:
      enabled: true
      middleware: []
      permissions: [post.view.user]
      path: /get-notification-page
    SendFCM:
      enabled: true
      middleware: []
      permissions: [post.view.user]
      path: /send-fcm
    SubscribeToTopic:
      enabled: true
      middleware: []
      permissions: [post.view.user]
      path: /subscribe-to-topic

